## configuracion de red para comunicacion entre contenedores
networks:
    backend:
        driver: bridge

services:
    postgres:
        image: postgres:14-alpine
        container_name: postgres
        hostname: postgres
        restart: always
        env_file:
            -   path: .env
                required: true
        #ports:
        # - 5432:5432 # descomentar para acceder a la base de datos desde el host
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - backend

    api:
        image: api
        container_name: api
        hostname: api
        restart: always
        depends_on:
            - postgres
        ports:
            - 8080:8080
            - 8081:8081
        build:
            context: .
            dockerfile: Api/Dockerfile
        env_file:
            -   path: .env
                required: true
        networks:
            - backend

    testproject:
        image: testproject
        build:
            context: .
            dockerfile: TestProject/Dockerfile
        depends_on:
            - postgres
        networks:
            - backend

## volumenes para persistencia de datos
volumes:
    postgres-data:
        driver: local
        driver_opts:
            type: none
            device: ./Postgres/data
            o: bind

